#!/bin/bash

echo "【提示】正在检查docker是否启动，若未启动，将为你启动"
sudo service docker status
if [ "$?" -eq 1 ]; then
    sudo service docker start;
fi

i=1;
j=$#;

# Make sure only one argument is passed.
if [ $j -gt 1 ]
then
    echo "Too many arguments. Only '--build' allowed in order to rebuild the VM.";
    exit;
fi

# If the '--build' argument is passed, rebuild the VM.
if [ "$1" = "--build" ]
then
    docker-compose up --build -d;
# If the argument is empty, regularly start the VM.
elif [ -z $1 ]
then
    docker-compose up -d;

# If something else is given as the argument, abort the script.
else
    echo "Incorrect argument. Either provide no arguments or '--build' as the single argument in order to rebuild the VM."
fi
